spring:
  redis:
    host: 127.0.0.1 #Redis服务器地址↓
    port: 6379 #Redis服务器连接端口↓.
    database: 0 #Redis.数据库索引(默认为日)↓
    timeout: 1800000 #连接超时时间(毫秒)↓
    lettuce:
      pool:
        max-active: 20 #连接池最大连接数(使用负值表示没有限制)
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)↓
        max-idle: 5 #连接池中的最大空闲连接:
        min-idle: 0 #连接池中的最小空闲连接:


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT&allowMultiQueries=true
    #url: jdbc:mysql://atopa.top:1104/test?serverTimezone=GMT&allowMultiQueries=true
    username: root
    password: 123456

mybatis-plus:
  global-config: # 假删除
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml #扫描所有mybatis文件